version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10
    working_directory: ~/gitlab-artifact-remover
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/gitlab-artifact-remover
  lint:
    docker:
      - image: circleci/node:10
    working_directory: ~/gitlab-artifact-remover
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/gitlab-artifact-remover
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run build

  release:
    docker:
      - image: circleci/node:10
    steps:
      - run: echo "hello world"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - lint
      - hold:
          type: approval
          requires:
            - build
      - release:
          requires:
            - hold
