version: 2
jobs:
  install:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: npm install

  lint:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: npm run lint

  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: npm run build

  release:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: echo "hello world"

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - hold:
          type: approval
          requires:
            - build
      - release:
          requires:
            - hold
